### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by detjensrobert** [cs361-stock-prediction/stock-predictor#17]
Due Date: ASAP
Prerequisites: #1 
Estimated time: 1h

We need to agree on the structure of the server API so the client can request data.
Something like `site.com/api/stockdata?ticker=TICKER`, etc

# API Events

### Requests
- [ ] Stock data
- [ ] Stock prediction
- [ ] Is this stock saved to the current user?
- [ ] What are the stocks this user has saved?
### Posts
- [ ] Save stock to current user
- [ ] Login
- [ ] New accounr

**Comment by lyellread** [comment]
@detjensrobert I found [this](https://help.parsehub.com/hc/en-us/articles/217751808-API-Tutorial-How-to-get-run-data-using-Python-Flask) and [this(better)](https://blog.miguelgrinberg.com/post/designing-a-restful-api-with-python-and-flask). Looks like we should use `.../api/stockdata/$TICKER` for example. How does this sound.

**Comment by detjensrobert** [comment]
and account stuff under `/api/accounts/$USN`, e.g. to add a stock to an account?

Works for me.

**Comment by lyellread** [comment]
> and account stuff under `/api/accounts/$USN`, e.g. to add a stock to an account?

I would go with `/api/stockadd/account/stock`,

**Comment by detjensrobert** [comment]
Gonna update the readme with the api docs on `api-docs`
